name: Damage Calculation Test

#実行するタイミング(ブランチマスターにプッシュされたとき)
on:
  push:
    branches: [ master ]

#やること　(ビルドをする)
jobs:
  build:
    #ubuntuでサーバーを起動する
    runs-on: ubuntu-latest
    
    #何をしていくか(チェックアウト、一連の動作に名前をつける、nodeのセットアップ)
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v14.15.4
      uses: actions/setup-node@v1
      with:
        node-version: '14.15.4'
    
    #yarnインストールとテストを実行
    - run: yarn install
    - run: yarn test
